# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redmine_project_support_hours}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Davis"]
  s.date = %q{2009-10-14}
  s.description = %q{Project Support Hours is a plugin to implement per-project buckets of hours that are used for support.}
  s.email = %q{edavis@littlestreamsoftware.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "COPYRIGHT.txt",
     "CREDITS.txt",
     "GPL.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/views/project_support_hours/_sidebar.html.erb",
     "app/views/settings/_project_support_hours.html.erb",
     "config/locales/en.yml",
     "init.rb",
     "lang/en.yml",
     "lib/project_support_hours/calculator.rb",
     "lib/project_support_hours/hooks/external_signups_hooks.rb",
     "lib/project_support_hours/hooks/project_hooks.rb",
     "lib/project_support_hours/mapper.rb",
     "rails/init.rb",
     "test/exemplars/custom_field_exemplar.rb",
     "test/exemplars/custom_value_exemplar.rb",
     "test/exemplars/enumeration_exemplar.rb",
     "test/exemplars/project_exemplar.rb",
     "test/exemplars/time_entry_activity.rb",
     "test/exemplars/time_entry_exemplar.rb",
     "test/exemplars/user_exemplar.rb",
     "test/integration/project_overview_hooks_test.rb",
     "test/test_helper.rb",
     "test/unit/lib/project_support_hours/calculator_test.rb",
     "test/unit/lib/project_support_hours/hooks/external_signups_create_hooks_test.rb",
     "test/unit/lib/project_support_hours/hooks/external_signups_update_hooks_test.rb",
     "test/unit/lib/project_support_hours/hooks/project_hooks_test.rb",
     "test/unit/lib/project_support_hours/mapper_test.rb",
     "test/unit/sanity_test.rb"
  ]
  s.homepage = %q{https://projects.littlestreamsoftware.com/projects/TODO}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{redmine_project_support_hours}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Project Support Hours is a plugin to implement per-project buckets of hours that are used for support.}
  s.test_files = [
    "test/unit/lib/project_support_hours/hooks/external_signups_create_hooks_test.rb",
     "test/unit/lib/project_support_hours/hooks/external_signups_update_hooks_test.rb",
     "test/unit/lib/project_support_hours/hooks/project_hooks_test.rb",
     "test/unit/lib/project_support_hours/calculator_test.rb",
     "test/unit/lib/project_support_hours/mapper_test.rb",
     "test/unit/sanity_test.rb",
     "test/integration/project_overview_hooks_test.rb",
     "test/exemplars/custom_field_exemplar.rb",
     "test/exemplars/enumeration_exemplar.rb",
     "test/exemplars/project_exemplar.rb",
     "test/exemplars/user_exemplar.rb",
     "test/exemplars/time_entry_exemplar.rb",
     "test/exemplars/time_entry_activity.rb",
     "test/exemplars/custom_value_exemplar.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
